name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Jenkins
        uses: snow-actions/setup-jenkins@v1.1.0
        # Add additional configuration options here if necessary
